version: '3.3'
services:
  kue:
    image: redis:3-alpine
    restart: always
  zen:
    image: node:carbon
    working_dir: /usr/src/app
    ports:
      - '8000:8000'
    env_file: ./workspace-zen/cp-zen-platform/web/config/development.env
    command: yarn dev
    depends_on:
      - users
      - dojos
      - events
      - badges
      - frontend
      - eventbrite
      - organisations
      - events-service
      - maildev
      - email
    environment:
      - CD_USERS=users
      - CD_DOJOS=dojos
      - CD_EVENTS=events
      - CD_BADGES=badges
      - CD_EVENTBRITE=eventbrite
      - CD_ORGANISATIONS=organisations
      - EVENTS_SERVICE=events-service
      - EMAIL_SERVICE=email
      - NODE_ENV=development
      - MAILDEV_ENABLED=false
    volumes:
      - ./workspace-zen/cp-zen-platform:/usr/src/app:Z
      - ./workspace-zen/cp-zen-frontend:/usr/src/app/node_modules/cp-zen-frontend:ro
      - ./workspace-zen/cp-translations:/usr/src/app/node_modules/cp-translations:ro
  frontend:
    image: node:carbon
    command: yarn dev
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./workspace-zen/cp-zen-frontend:/usr/src/app:Z
      - ./workspace-zen/cp-translations:/usr/src/app/node_modules/cp-translations:ro
  dojos:
    image: node:carbon
    env_file: ./workspace-zen/cp-dojos-service/config/development.env
    working_dir: /usr/src/app
    command: yarn dev
    environment:
      - NODE_ENV=development
      - CD_USERS=users
      - CD_EVENTS=events
      - CD_BADGES=badges
      - CD_ORGANISATIONS=organisations
      - POSTGRES_HOST=db
      - KUE_REQUIRED='true'
      - KUE_HOST=kue
      - GOOGLE_MAPS_KEY=AIzaSyD8o-96eWjZmmQnSpKMMPXR93ycx4XafIw
      - MAILDEV_ENABLED=false
    depends_on:
      - kue
    volumes:
      - ./workspace-zen/cp-dojos-service:/usr/src/app:Z
      - ./workspace-zen/cp-translations:/usr/src/app/node_modules/cp-translations:ro
  users:
    image: node:carbon
    env_file: ./workspace-zen/cp-users-service/config/development.env
    working_dir: /usr/src/app
    command: yarn dev
    environment:
      - NODE_ENV=development
      - CD_DOJOS=dojos
      - CD_EVENTS=events
      - CD_BADGES=badges
      - POSTGRES_HOST=db
      - CDF_ADMINS=oana.vasilache@coderdojo.ro
      - MAILDEV_ENABLED=false
      - MAIL_USER=no_reply@coderdojo.ro
      - MAIL_PASS=tAi4GVEDYCioLQpq
    volumes:
      - ./workspace-zen/cp-users-service:/usr/src/app:Z
      - ./workspace-zen/cp-translations:/usr/src/app/node_modules/cp-translations:ro
  events:
    image: node:carbon
    env_file: ./workspace-zen/cp-events-service/config/development.env
    working_dir: /usr/src/app
    command: yarn dev
    environment:
      - CD_USERS=users
      - CD_DOJOS=dojos
      - CD_BADGES=badges
      - NODE_ENV=development
      - POSTGRES_HOST=db
      - KUE_REQUIRED='true'
      - KUE_HOST=kue
    depends_on:
      - kue
    volumes:
      - ./workspace-zen/cp-events-service:/usr/src/app:Z
  badges:
    image: node:carbon
    working_dir: /usr/src/app
    env_file: ./workspace-zen/cp-badges-service/config/development.env
    command: yarn dev
    environment:
      - CD_USERS=users
      - CD_DOJOS=dojos
      - CD_EVENTS=events
      - NODE_ENV=development
    volumes:
      - ./workspace-zen/cp-badges-service:/usr/src/app:Z
      - ./workspace-zen/cp-translations:/usr/src/app/node_modules/cp-translations:ro
  eventbrite:
    image: node:carbon
    command: yarn dev
    env_file: ./workspace-zen/cp-eventbrite-service/config/development.env
    working_dir: /usr/src/app
    environment:
      - CD_DOJOS=dojos
      - CD_EVENTS=events
      - NODE_ENV=development
    volumes:
      - ./workspace-zen/cp-eventbrite-service:/usr/src/app:Z
      - ./workspace-zen/cp-translations:/usr/src/app/node_modules/cp-translations:ro
  organisations:
    image: node:carbon
    command: yarn dev
    working_dir: /usr/src/app
    env_file: ./workspace-zen/cp-organisations-service/config/development.env
    environment:
      - CD_USERS=users
      - NODE_ENV=development
      - POSTGRES_HOST=db
    volumes:
      - ./workspace-zen/cp-organisations-service:/usr/src/app:Z
      - ./workspace-zen/cp-translations:/usr/src/app/node_modules/cp-translations:ro
  events-service:
    image: node:carbon
    command: yarn dev
    working_dir: /usr/src/app
    volumes:
      - ./workspace-zen/services/events-service:/usr/src/app:Z
  maildev:
    image: djfarrelly/maildev
    ports:
      - '1080:80'
  email:
    image: node:carbon
    command: yarn dev
    working_dir: /usr/src/app
    environment:
      - URL_BASE=http://localhost:8000
      - EMAIL_DEFAULT_FROM=no-reply@easybill.ro
      - MICROSERVICE_PORT=3000
      - TRANSPORT=ses
      - SMTP_HOST=email-smtp.eu-west-1.amazonaws.com
      - TEMPLATES_DIR=/usr/src/app/node_modules/cp-translations/email-templates
      - SMTP_SECURE=true
      - SMTP_PORT=25
      - SMTP_USER=AKIAIWHNOA4LVUESGLJA
      - SMTP_PASS=AoRNfAoim7TyNkHca1CowLNTgaVA9H635ZMej6LJEVtJ
      - AWS_KEY=AKIAIMQNTXJJNYZBRFUA
      - AWS_SECRET=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
      - AWS_REGION=eu-west-1
      - MAIL_USER=AKIAIWHNOA4LVUESGLJA
      - MAIL_PASS=AoRNfAoim7TyNkHca1CowLNTgaVA9H635ZMej6LJEVtJ

    volumes:
      - ./workspace-zen/services/cp-email-service:/usr/src/app:Z
      - ./workspace-zen/cp-translations:/usr/src/app/node_modules/cp-translations:ro
volumes:
  pg-data:
